#############################################################################
# Makefile for building: dist/TetraMesh
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  TetraMesh.pro
# Template: app
# Command: /Users/ciccio/Qt/5.4/clang_64/bin/qmake -spec macx-clang-omp CONFIG+=x86_64 -o Makefile TetraMesh.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
CXX           = /usr/local/bin/clang-omp
DEFINES       = 
CFLAGS        = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10 $(DEFINES)
CXXFLAGS      = -stdlib=libc++ -fpermissive -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -std=c++0x -mmacosx-version-min=10.10 $(DEFINES)
INCPATH       = -I../../../../Qt/5.4/clang_64/mkspecs/macx-clang-omp -I.
QMAKE         = /Users/ciccio/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = TetraMesh1.0.0
DISTDIR = /Users/ciccio/Dropbox/Programs/StableLibraries/TetraMesh/build/TetraMesh1.0.0
LINK          = /usr/local/bin/clang-omp
LFLAGS        = -lstdc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.10
LIBS          = $(SUBLIBS)  
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = source/Mesh.cpp \
		source/IO.cpp \
		main.cpp 
OBJECTS       = build/Mesh.o \
		build/IO.o \
		build/main.o
DIST          = ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/g++-macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang-omp/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		TetraMesh.pro source/Define.h \
		source/Edge.h \
		source/Mesh.h \
		source/Tetra.h \
		source/Triangle.h \
		source/Vertex.h source/Mesh.cpp \
		source/IO.cpp \
		main.cpp
QMAKE_TARGET  = TetraMesh
DESTDIR       = dist/#avoid trailing-slash linebreak
TARGET        = dist/TetraMesh

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-std=c++0x \
		-mmacosx-version-min=10.10



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d dist/ || mkdir -p dist/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TetraMesh.pro ../../../../Qt/5.4/clang_64/mkspecs/macx-clang-omp/qmake.conf ../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/g++-base.conf \
		../../../../Qt/5.4/clang_64/mkspecs/common/g++-macx.conf \
		../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/macx-clang-omp/qmake.conf \
		../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		TetraMesh.pro
	$(QMAKE) -spec macx-clang-omp CONFIG+=x86_64 -o Makefile TetraMesh.pro
../../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/g++-base.conf:
../../../../Qt/5.4/clang_64/mkspecs/common/g++-macx.conf:
../../../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/macx-clang-omp/qmake.conf:
../../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
TetraMesh.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang-omp CONFIG+=x86_64 -o Makefile TetraMesh.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) dist/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

build/Mesh.o: source/Mesh.cpp source/Mesh.h \
		source/Tetra.h \
		source/Triangle.h \
		source/Edge.h \
		source/Vertex.h \
		source/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Mesh.o source/Mesh.cpp

build/IO.o: source/IO.cpp source/Mesh.h \
		source/Tetra.h \
		source/Triangle.h \
		source/Edge.h \
		source/Vertex.h \
		source/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/IO.o source/IO.cpp

build/main.o: main.cpp source/Mesh.h \
		source/Tetra.h \
		source/Triangle.h \
		source/Edge.h \
		source/Vertex.h \
		source/Define.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

